### ISSUE TITLE
Seeeduino AVR v1.1.2 fails to install

### ISSUE THREAD

**Issue by BWibo** [Seeed-Studio/Seeed_Platform#13]
Hey there,
the Arduino IDE board manager setup of *Seeeduino AVR* boards fails for version 1.1.2.

![err](https://user-images.githubusercontent.com/7643434/56735830-dc307880-6766-11e9-932c-1e0d3eddb5c4.jpg)

The URL 
https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/Seeeduino_AVR_v1.1.2.tar.bz2 is dead.
However, a file for a more recent version (1.2.1) appears to be available on the repo.
https://github.com/Seeed-Studio/Seeed_Platform/blob/master/Seeeduino_AVR_v1.2.1.tar.bz2

Please add the more recent version to `package_seeeduino_boards_index.json` or provide the file for version 1.1.2.

Moreover, when using Seeeduino AVR v1.1.0 the *Seeeduino Lotus* (not the M0 versions) is missing from the list of available board in Arduino IDE.

Big thx in advance,
Bruno

**Comment by mallodu55** [comment]
I have the same problem ! 

Please resolve this problem as soon as possible because now I can’t use my Seeeduino V4.2 ...

**Comment by Pillar1989** [comment]
We are sorry for that. You can try again, it should be ready now.

**Comment by BWibo** [comment]
I can confirm it is working, thx for the fix. 
However, the Seeeduino Lotus AVR Version is still missing form the list of supported bords in `v1.21`.

**Comment by BWibo** [comment]
I can confirm it is working now, thx for the fix.
However, the *Seeeduino Lotus AVR board* is still missing in the list of supported boards (in the board manager only). This makes it harder to find the right package to download for this board and may lead to people downloading the M0 version, where the Lotus board is listed.

**Comment by linux-downey** [comment]
Sorry for the inconvenience of your work. Our team has fixed the bug, you can use it now.@BWibo

**Comment by BWibo** [comment]
Hey there, thx for the quick fix. I can confirm it is working now.

**Comment by achaggi** [comment]
Hi Pillar1989, 

I've used this url for additional boards in Arduino IDE: 

https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json

It doesn't list seeeeduino avr boards. It doesn't show anything on the board manager. I'm a newbie to this, so please let me know if I'm doing something wrong. 

I'm trying to install Lotus board.
