### ISSUE TITLE
 package_seeeduino_boards_index.json : Compiling for the Seeeduino LoRaWAN fails in the Arduido IDE after commit 64598788b967c5c03d3b45138d1e57679195ed85

### ISSUE THREAD

**Issue by kingigi** [Seeed-Studio/Seeed_Platform#17]
It seems that a lot of board definitions have changed in commit 64598788b967c5c03d3b45138d1e57679195ed85
The board definition for the Seeeduino LoraWAN is missing now.
This causes the compilation in the Arduino IDE to fail, because it is configured to use the  package_seeeduino_boards_index.json on GitHub as a board definition-file.

Was this change intentional?
If so, then I think the Wiki for the Seeeduino LoRaWAN needs a link to a working board definition.

**Comment by enguy-hub** [comment]
I am also experiencing this issue, could someone please look into it ?

**Comment by kingigi** [comment]
I think @LynnL4  is the one who is the most qualified to look at this?

**Comment by kingigi** [comment]
As a work-around I used this URL to use the previous board definition:
https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/e9b9f61c88ae990d88b12760d59d0a7be607d251/package_seeeduino_boards_index.json

**Comment by enguy-hub** [comment]
@kingigi That is great ! Thank you for your suggestion :D

**Comment by LynnL4** [comment]
you can use this new url. https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

**Comment by kingigi** [comment]
Hi @LynnL4,
Thanks for the new link.
The Wiki ( https://wiki.seeedstudio.com/Seeed_Arduino_Boards/ ) still points to the old URL.
Is this something you can fix too?
kind regards,
    Egon
