### ISSUE TITLE
Seeduino LoRaWAN/SAMD boards wiped from arduino envrionment

### ISSUE THREAD

**Issue by Bailey-Coole** [Seeed-Studio/Seeed_Platform#18]
Hi

The latest commit broke my setup, redirecting my arduino IDE's board manager URL's to :
https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/e9b9f61c88ae990d88b12760d59d0a7be607d251/package_seeeduino_boards_index.json
Fixed the issues, appears to be intentional change?

 Are these boards no longer being supported or will a different .json file be needed to add them?

**Comment by LynnL4** [comment]
Sorry, Please use this address https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
