### ISSUE TITLE
"Seeeduino SAMD"  is missing from the json file and it disappeared from board manager

### ISSUE THREAD

**Issue by abervan** [Seeed-Studio/Seeed_Platform#19]
"Seeeduino SAMD"  is missing from the "package_seeeduino_boards_index.json" file and I can't find the Seeeduino SAMD in the board manager in Arduino IDE.

**Comment by LynnL4** [comment]
Sorry about that, Please use this link https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
