### ISSUE TITLE
Cannot load Wio Terminal and Seeeduino boards into the IDE at the same time

### ISSUE THREAD

**Issue by JustAskSmith** [Seeed-Studio/Seeed_Platform#20]
Please see https://wiki.seeedstudio.com/Seeed_Arduino_Boards/ and try to put both URLs into the Arduino IDE board manager. You will only see boards from one of the two sources because the board files have the same file name. The IDE overwrites its local copy of the first one downloaded with the second one so only one gets processed.
SAMD series:
https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
Others:
https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json

I worked around this by creating a local copy of the second board file and renamed it to package_seeduino_boards1_index.json. But this is not a good fix as I am now disconnected from updates.

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/Seeed_Platform/commit/7d8cd4fdabd5fe9f01f6b06fc06e6d3eacd9e5f2
