### ISSUE TITLE
Renaming platform file breaks all links

### ISSUE THREAD

**Issue by martenbiehl** [Seeed-Studio/Seeed_Platform#21]
Hi,

the following commit breaks all existing links on your wiki/tutorial pages.
https://github.com/Seeed-Studio/Seeed_Platform/commit/7d8cd4fdabd5fe9f01f6b06fc06e6d3eacd9e5f2

Related to #8 ?

Is the Wio LTE considered legacy by now?

Best
Marten

**Comment by Pillar1989** [comment]
Changing the file name does not affect internal links.

**Comment by martenbiehl** [comment]
The file path including the name is used in all your guides as an external path in the board manager. 

new path to this file to add to the board manager according to your support is: https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_legacy_seeeduino_boards_index.json

This has not been updated in the following place:
 https://github.com/Seeed-Studio/WioLTE_Cat_NB1_Arduino_Library

https://wiki.seeedstudio.com/Seeed_Arduino_Boards/ (this has been fixed now)

This is quite the problem for getting Wio LTE Cat M1/NB-IoT running which is not considered legacy yet, right?

**Comment by Pillar1989** [comment]
@martenbiehl  I'm really sorry that our hasty modification caused an error. You can delete the board and try again.
