### ISSUE TITLE
404 on board manager url

### ISSUE THREAD

**Issue by naldoxable** [Seeed-Studio/Seeed_Platform#22]
Hi, the link below, used in arduino is not valid. 404
https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json

**Comment by jreyesa0901** [comment]
Still waiting for the update.
I found though this that has some of the legacy boards: https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_legacy_seeeduino_boards_index.json

Anyhow the most updated one is still 404.

**Comment by lamachine** [comment]
Still missing.  Bump!

**Comment by virtualdxs** [comment]
It seems the legacy one is what used to be the updated one, see commit 7d8cd4f. Any explanation as to why this is now considered legacy?

**Comment by virtualdxs** [comment]
Looks like the new URL is here: https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

Based on: https://wiki.seeedstudio.com/Seeeduino-XIAO/
