### ISSUE TITLE
Installation with Boards Manager is incomplete

### ISSUE THREAD

**Issue by ZinggJM** [Seeed-Studio/Seeed_Platform#4]
I installed Seeeduino 1.0.0 with Boards Manager on Arduino 1.8.4 on Windows 10.
The installation is incomplete, only boards.txt and platforms.txt in directory 1.0.0.

And I do not know which ATmega16u2 hex file should be programmed to this non-programmed device.

**Comment by KillingJacky** [comment]
Please see https://github.com/Seeed-Studio/Signed_USB_Serial_Driver/issues/1
