### ISSUE TITLE
libraries in RePhone_core_2G_MT2502_v1.0.0.tar.bz2 not updated

### ISSUE THREAD

**Issue by cntlsn** [Seeed-Studio/Seeed_Platform#5]
Hello,

Could you please update https://github.com/Seeed-Studio/Seeed_Platform/blob/master/RePhone_core_2G_MT2502_v1.0.0.tar.bz2 with the updated libraries in https://github.com/Seeed-Studio/Arduino_IDE_for_RePhone/tree/master/hardware/arduino/mtk/libraries

Thanks a lot

**Comment by WayenWeng** [comment]
It had been updated. Thanks!

**Comment by cntlsn** [comment]
great, thanks!
