### ISSUE TITLE
Problem with board manager

### ISSUE THREAD

**Issue by domo667** [Seeed-Studio/Seeed_Platform#8]
Hello, when i try to use board manager i get error 

Error downloading https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json

am i doing something wrong?

edit: i'd like to add, that it worked just three days ago, and then it stopped.

**Comment by KillingJacky** [comment]
Hi @domo667 , it seems to be a network issue.
